name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-test:
    name: ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          # Linux
          - os: linux
            arch: x64
            runner: ubuntu-24.04
            target: x86_64-unknown-linux-gnu
          - os: linux
            arch: arm64
            runner: ubuntu-24.04-arm
            target: aarch64-unknown-linux-gnu

          # Windows
          - os: windows
            arch: x64
            runner: windows-latest
            target: x86_64-pc-windows-msvc
          - os: windows
            arch: arm64
            runner: windows-latest
            target: aarch64-pc-windows-msvc

          # macOS
          #- os: macos
          #  arch: x64
          #  runner: macos-13
          #  target: x86_64-apple-darwin
          - os: macos
            arch: arm64
            runner: macos-14
            target: aarch64-apple-darwin

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Rust nightly
        run: |
          rustup toolchain install nightly --profile minimal --target ${{ matrix.target }}
          rustup default nightly
          rustc -V
          cargo -V

      - name: Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-${{ matrix.arch }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build
        run: cargo build --release

      - name: Test
        run: cargo test --all

      - name: Bench
        run: cargo bench
